# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
#  - 0.6
  - 0.7
  - 1.0
#  - nightly
env:
  - JULIA_PROJECT="@."
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      if VERSION >= v"0.7.0-DEV.5183"
          pkg"activate ."
          pkg"instantiate"
          Pkg.build("TestSimpleJuliaPkgOnCI"); Pkg.test("TestSimpleJuliaPkgOnCI", coverage=true)
      else
          Pkg.clone(pwd()); Pkg.build("TestSimpleJuliaPkgOnCI"); Pkg.test("TestSimpleJuliaPkgOnCI"; coverage=true)
      end'
